name: Publish Docker image
on: [push]
permissions: write-all
#  packages: write
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # push was 403
          password: ${{ secrets.GITHUB_TOKEN }}
#          username: ${{ github.repository_owner }} #login denied
#          password: ${{ secrets.GHCR_TOKEN }}
#          username: ${{ github.repository_owner }} #login: Username and password required
#          password: ${{ secrets.CR_PAT }}
#          username: ${{ github.repository_owner }} #login: Username and password required
#          password: ${{ secrets.GITHUB_REGISTRY_TOKEN }}
#          username: ${{ github.repository_owner }}  # push was 403
#          password: ${{ secrets.GITHUB_TOKEN }}
#          username: ${{ github.actor }} # push was 403
#          password: ${{ secrets.GHCR_TOKEN }}
      - name: Push to GitHub Packages v2
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:v2
      - name: Push to GitHub Packages v3
        uses: docker/build-push-action@v3
        with:
          file: ./v3.dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:v3