name: Publish Docker image
on: [push]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build-push v3
        uses: docker/build-push-action@v3
        with:
          file: ./v3.dockerfile
          push: true
          tags: ghcr.io/conecenter/c4replink:v3
      - name: build-push v3k
        uses: docker/build-push-action@v3
        with:
          file: ./v3k.dockerfile
          push: true
          tags: ghcr.io/conecenter/c4replink:v3k,ghcr.io/conecenter/c4replink:v3kc

#          tags: ghcr.io/${{ github.repository }}:v3

# push was failing after login with 403
# https://github.com/orgs/community/discussions/26274
# to fix this, head over to $yourOrganization → Packages → $yourPackage → Package settings (to the right / bottom)
# https://github.com/orgs/conecenter/packages/container/c4replink/settings
# And configure “Manage Actions access” section to give the git repository write permissions
